name: sunackubaru
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  slang: ^3.19.0
  slang_flutter: ^3.19.0

dev_dependencies:
  blackfoot_flutter_lint: ^1.1.0
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  slang_build_runner: ^3.19.0

flutter:
  uses-material-design: true

scripts:
  run: flutter run -d macos --dart-define-from-file=env.json
  analyze: flutter analyze
  get: flutter pub get
  gen:
    build: flutter pub run build_runner build --delete-conflicting-outputs
    watch: flutter pub run build_runner watch --delete-conflicting-outputs
  start:
    debug: flutter run -d macos --dart-define-from-file=env.json
    release: flutter run -d macos --dart-define-from-file=env.json --release
  test: flutter test -d macos --dart-define-from-file=env.json
